### ISSUE TITLE
could not jump to the explorer

### ISSUE THREAD

**Issue by 1925381584** [idkidknow/Flow.Launcher.Plugin.DirQuickJump#1]
Hei, when I press the enter in the results interface,but nothing happen. 

OS: Windows 10.0.19045
emacs version : 30.0.50
DirQuickJump: 1.0.0

![image](https://github.com/user-attachments/assets/e1675944-7011-4529-997f-f3583eb9b55a)

**Comment by idkidknow** [comment]
It appears that Emacs is utilizing `GetOpenFilename`/`GetSaveFilename` from `commdlg.h` with the flags `OFN_EXPLORER` and `OFN OFN_ENABLEHOOK` to create Windows common dialogs, which results in old-style dialog windows without an editable address bar.
I am considering to use the filename text box to jump within these legacy dialogs.

**Comment by idkidknow** [comment]
> I see you update the version here, but it hasn't been updated in the store yet, is there some process I still need to wait for?

See https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/blob/plugin_api_v2/README.md

> Flow downloads the plugins manifest file from various CDN providers, so when your new plugin appears is dependant on when these providers next sync the updated file, and this can be anywhere from one to three hours.
