### ISSUE TITLE
Can you please provide more info how it should work?

### ISSUE THREAD

**Issue by oremir** [idkidknow/Flow.Launcher.Plugin.DirQuickJump#2]

**Comment by idkidknow** [comment]
I added a gif to the readme just now, which should clearly demonstrate the usage.

It should work in that kind of dialog boxes, because it merely simulates the Alt+D shortcut key, followed by entering the path and pressing Enter.

**Comment by oremir** [comment]
Thank you but looks like it still doesn´t work for me
![ezgif-5-c9349f6a1d](https://github.com/user-attachments/assets/e361cf10-b470-4fa7-b922-169f731e3f45)

**Comment by idkidknow** [comment]
I reproduced the issue after switching to the Czech keyboard. It is speculated that AltGr was used incorrectly.
